apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sysdigcloud-cassandra
  labels:
    app: sysdigcloud
spec:
  serviceName: cassandra
  replicas: 3
  selector:
    matchLabels:
      app: sysdigcloud
  template:
    metadata:
      labels:
        app: sysdigcloud
        role: cassandra
    spec:
      containers:
        - image: quay.io/sysdig/cassandra:2.1.15.0
          name: cassandra
          #resources:
          #  limits:
          #    cpu: "500m"
          #    memory: 1Gi
          #  requests:
          #   cpu: "500m"
          #   memory: 1Gi        
          env:
            - name: CASSANDRA_SERVICE
              value: sysdigcloud-cassandra
            - name: CASSANDRA_NUM_SEEDS
              value: "2"
            - name: CASSANDRA_CLUSTER_NAME
              value: sysdigcloud
            #- name: MAX_HEAP_SIZE
            #  value: 512M
            #- name: HEAP_NEWSIZE
            #  value: 100M 
            # If not using CASSANDRA_SERVICE discovery, manually configure the seeds
            # - name: CASSANDRA_SEEDS
            #   value: ""
            # If using multiple directories for data, set the path list
            # - name: CASSANDRA_DATA_DIRS
            #   value: "/var/lib/cassandra/data /var/lib/cassandra/data2"
            - name: JVM_EXTRA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: cassandra.jvm.options
            - name: CASSANDRA_SECURE
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: cassandra.secure
            - name: CASSANDRA_SSL
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: cassandra.ssl.enabled
          volumeMounts:
            - mountPath: /var/lib/cassandra
              name: data
            # Uncomment this when using multiple mount points for data
            # - mountPath: /var/lib/cassandra/data2
            #   name: data
      imagePullSecrets:
        - name: sysdigcloud-pull-secret
      #volumes:
        # Uncomment this for emptyDir volumes
        #- name: data
        #  emptyDir: {}
        #- name: data
        #  persistentVolumeClaim:
        #   claimName: sysdigcloud-cas-pv-claim           
        # - name: data2
        #   emptyDir: {}
        # Uncomment this for hostPath volumes
        # - name: data
        #   hostPath:
        #     path: /mnt/data
        # - name: data2
        #   hostPath:
        #     path: /mnt/data2
        # Uncomment this for GCE Disk
        # - name: data
        #   gcePersistentDisk:
        #     pdName: <volume-name>
        #     fsType: ext4
        # Uncomment this for AWS EBS
        #- name: data
        #  awsElasticBlockStore:
        #    volumeID: vol-0e0814693eaae3a10
        #    fsType: ext4
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: aws-gp2
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
